Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

### **Q1. Is there any difference in the data type of variables `list_` and `array_list`? If there is, then write a code to print the data types of both the variables.**

**Answer:**
Yes, there is a difference in the data type of `list_` and `array_list`. The `list_` variable is a Python list, while `array_list` is a NumPy array. We can check their data types using the `type()` function.

```python
import numpy as np

# Creating a list
list_ = ['1', '2', '3', '4', '5']

# Creating a NumPy array from the list
array_list = np.array(object=list_)

# Printing data types of both variables
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))
```

**Output:**
```
Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>
```

---

### **Q2. Write a code to print the data type of each and every element of both the variables `list_` and `array_list`.**

**Answer:**
To check the data type of each element, we iterate through both `list_` and `array_list` and use the `type()` function.

```python
# Printing data type of each element in list_
print("Data types of elements in list_:")
for i in list_:
    print(type(i))

# Printing data type of each element in array_list
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))
```

**Output:**
```
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
```

**Explanation:**
- `list_` elements are of type `str` (Python string).
- `array_list` elements are of type `numpy.str_`, which is a NumPy-specific string type.

---

### **Q3. Considering the following changes in the variable, `array_list`:**
```python
array_list = np.array(object = list_, dtype = int)
```
**Will there be any difference in the data type of the elements present in both variables, `list_` and `array_list`? If so, print the data types of each and every element present in both variables.**

**Answer:**
Yes, after specifying `dtype=int`, the elements of `array_list` will be converted from strings to integers.

```python
# Creating a NumPy array with integer type
array_list = np.array(object=list_, dtype=int)

# Printing data type of each element in list_
print("Data types of elements in list_:")
for i in list_:
    print(type(i))

# Printing data type of each element in array_list
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))
```

**Output:**
```
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
```

**Explanation:**
- `list_` elements remain `str` (strings).
- `array_list` elements are now `numpy.int64` because of `dtype=int`.

---

### **Q4. Write a code to find the following characteristics of variable `num_array`:**
(i) **Shape**  
(ii) **Size**  

**Answer:**
```python
import numpy as np

# Creating a nested list and converting it into a NumPy array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Printing shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)
```

**Output:**
```
Shape of num_array: (2, 3)
Size of num_array: 6
```

**Explanation:**
- `shape` returns `(2,3)`, meaning there are **2 rows** and **3 columns**.
- `size` returns `6`, meaning the array has **6 elements** in total.

---

### **Q5. Write a code to create a NumPy array of a 3×3 matrix containing only zeros.**
**(Hint: The size of the array will be 9, and the shape will be (3,3).)**

**Answer:**
```python
import numpy as np

# Creating a 3x3 zero matrix
zero_matrix = np.zeros((3, 3))

# Printing the matrix
print("3x3 Zero Matrix:")
print(zero_matrix)
```

**Output:**
```
3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

**Explanation:**
- `np.zeros((3,3))` creates a **3×3 matrix** filled with zeros.

---

### **Q6. Create an identity matrix of shape (5,5) using NumPy functions.**
**(Hint: An identity matrix contains 1 diagonally and other elements will be 0.)**

**Answer:**
```python
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

# Printing the matrix
print("5x5 Identity Matrix:")
print(identity_matrix)
```

**Output:**
```
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
```

**Explanation:**
- `np.eye(5)` creates a **5×5 identity matrix**, where **only diagonal elements are 1** and all other elements are 0.

---